apiVersion: v1
kind: ServiceAccount
metadata:
  name: srijan-developer
  namespace: srijan-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: srijan-operator
  namespace: srijan-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: srijan-admin
  namespace: srijan-prod