apiVersion: v1
kind: Pod
metadata:
  name: srijan-frontend
  namespace: srijan-dev
  labels:
    app: frontend
    tier: web
    environment: dev
    version: v1.0
spec:
  containers:
    - name: srijan-frontend
      image: nginx:1.21
      ports:
        - containerPort: 80