apiVersion: v1
kind: Service
metadata:
  name: srijan-analytics-svc
  namespace: srijan-dev
  labels:
    app: srijan-analytics
spec:
  clusterIP: None
  selector:
    app: srijan-analytics
  ports:
    - port: 8080
      targetPort: 8080