apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: srijan-node-exporter
  namespace: srijan-dev
  labels:
    app: srijan-node-exporter
spec:
  selector:
    matchLabels:
      app: srijan-node-exporter
  template:
    metadata:
      labels:
        app: srijan-node-exporter
    spec:
      tolerations:
        - key: workload
          operator: Equal
          value: analytics
          effect: NoSchedule
      hostNetwork: true
      containers:
        - name: srijan-node-exporter
          image: prom/node-exporter:v1.7.0
          ports:
            - containerPort: 9100
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
          args:
            - "--path.procfs=/host/proc"
            - "--path.sysfs=/host/sys"
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys