apiVersion: apps/v1
kind: Deployment
metadata:
  name: srijan-backend-api
  namespace: srijan-dev
  labels:
    app: backend-api
    tier: backend
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
        tier: backend
        environment: dev
    spec:
      containers:
        - name: srijan-backend-api
          image: hashicorp/http-echo
          args:
            - "-text=Hello from srijan-backend-api"
            - "-listen=:8080"
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: srijan-db-secret
                  key: mysql-root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: srijan-db-secret
                  key: mysql-user
          volumeMounts:
            - name: srijan-app-config-vol
              mountPath: /etc/srijan-config
      volumes:
        - name: srijan-app-config-vol
          configMap:
            name: srijan-app-config