apiVersion: v1
kind: Service
metadata:
  name: srijan-backend-svc
  namespace: srijan-dev
  labels:
    app: backend-api
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: backend-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP