apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: srijan-ingress
  namespace: srijan-dev
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - srijan.local
      secretName: srijan-tls-secret
  rules:
    - host: srijan.local
      http:
        paths:
          - path: /vault
            pathType: Prefix
            backend:
              service:
                name: srijan-frontend-svc
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: srijan-backend-svc
                port:
                  number: 8080