apiVersion: v1
kind: ConfigMap
metadata:
  name: srijan-app-config
  namespace: srijan-dev
data:
  database-url: "srijan-mysql-0.srijan-mysql-svc.srijan-dev.svc.cluster.local:3306"
  cache-config: "cache-ttl=300;cache-size=100MB"
  api-settings: "rate-limit=1000;timeout=30s"