apiVersion: v1
kind: Secret
metadata:
  name: srijan-db-secret
  namespace: srijan-dev
type: Opaque
stringData:
  mysql-root-password: "srijanRootPass123"
  mysql-user: "srijan_app_user"
  mysql-password: "srijanAppPass456"