apiVersion: v1
kind: ConfigMap
metadata:
  name: srijan-mysql-init-schema
  namespace: srijan-dev
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS asset_catalog (
      id INT AUTO_INCREMENT PRIMARY KEY,
      asset_name VARCHAR(255) NOT NULL,
      asset_type VARCHAR(50),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    INSERT INTO asset_catalog (asset_name, asset_type) VALUES ('sample-digital-art', 'image');