apiVersion: v1
kind: Service
metadata:
  name: srijan-mysql-svc
  namespace: srijan-dev
  labels:
    app: srijan-mysql
spec:
  clusterIP: None
  selector:
    app: srijan-mysql
  ports:
    - port: 3306
      targetPort: 3306